import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

type ProductInput = {
  name: string
  category: string
  brand: string
  price: number
  description: string
  specifications: Record<string, string>
  pros: string[]
  cons: string[]
  rating: number
  reviews_count: number
  amazon_link?: string
  flipkart_link?: string
  in_stock?: boolean
}

function makeAmazonLink(q: string) {
  return `https://www.amazon.in/s?k=${encodeURIComponent(q)}&tag=maygunai-21`
}
function makeFlipkartLink(q: string) {
  return `https://www.flipkart.com/search?q=${encodeURIComponent(q)}`
}

const laptops: ProductInput[] = [
  { name: 'Apple MacBook Air M2 13"', category: 'Laptops', brand: 'Apple', price: 114900, description: 'Apple M2 chip with 8-core CPU and 8-core GPU. 18-hour battery life. Fanless design.', specifications: { Processor: 'Apple M2 8-core', RAM: '8GB Unified Memory', Storage: '256GB SSD', Display: '13.6" Liquid Retina', Battery: '18 hours', Weight: '1.24 kg', OS: 'macOS Ventura' }, pros: ['Exceptional battery life', 'Silent fanless design', 'Best-in-class performance per watt', 'Beautiful Retina display'], cons: ['Limited to 8GB RAM base', 'No upgrade option post-purchase', 'Only 2 Thunderbolt ports'], rating: 4.8, reviews_count: 12450 },
  { name: 'Dell XPS 15 9530', category: 'Laptops', brand: 'Dell', price: 189999, description: 'Intel Core i7-13700H, RTX 4060, 16GB DDR5, 4K OLED display. Premium ultrabook for creators.', specifications: { Processor: 'Intel Core i7-13700H', RAM: '16GB DDR5', Storage: '512GB NVMe SSD', Display: '15.6" 4K OLED Touch', GPU: 'NVIDIA RTX 4060 8GB', Battery: '86Whr', Weight: '1.86 kg' }, pros: ['Stunning 4K OLED display', 'Powerful RTX 4060 GPU', 'Premium build quality', 'Thunderbolt 4 ports'], cons: ['Very expensive', 'Average battery life', 'Gets warm under load'], rating: 4.6, reviews_count: 3210 },
  { name: 'ASUS ROG Zephyrus G14 2023', category: 'Laptops', brand: 'ASUS', price: 139999, description: 'AMD Ryzen 9 7940HS, RX 7600S, 16GB DDR5. Compact 14" gaming powerhouse with AniMe Matrix.', specifications: { Processor: 'AMD Ryzen 9 7940HS', RAM: '16GB DDR5', Storage: '1TB NVMe SSD', Display: '14" 2560x1600 165Hz', GPU: 'AMD RX 7600S 8GB', Battery: '76Whr', Weight: '1.65 kg' }, pros: ['Compact gaming powerhouse', 'Excellent display', 'Strong AMD performance', 'Good battery for gaming laptop'], cons: ['AniMe Matrix logo uses battery', 'Gets loud under full load', 'Limited port selection'], rating: 4.5, reviews_count: 2876 },
  { name: 'Lenovo ThinkPad X1 Carbon Gen 11', category: 'Laptops', brand: 'Lenovo', price: 159900, description: 'Business ultrabook with Intel vPro, 16GB LPDDR5, military-grade durability. Perfect for enterprise.', specifications: { Processor: 'Intel Core i7-1365U vPro', RAM: '16GB LPDDR5', Storage: '512GB PCIe SSD', Display: '14" 2K IPS Anti-glare', Battery: '57Whr', Weight: '1.12 kg', Connectivity: 'WiFi 6E, 4G LTE' }, pros: ['Lightest in class', 'Exceptional keyboard', 'Military-grade durability', 'vPro security features'], cons: ['Mediocre integrated graphics', 'Expensive', 'Display could be brighter'], rating: 4.7, reviews_count: 1890 },
  { name: 'HP Pavilion Gaming 15', category: 'Laptops', brand: 'HP', price: 69999, description: 'Intel Core i5-13500H, RTX 3050, 144Hz display. Budget gaming laptop for entry-level gamers.', specifications: { Processor: 'Intel Core i5-13500H', RAM: '8GB DDR4', Storage: '512GB SSD', Display: '15.6" FHD 144Hz IPS', GPU: 'NVIDIA RTX 3050 4GB', Battery: '52.5Whr', Weight: '2.25 kg' }, pros: ['Good 144Hz display', 'RTX 3050 handles most games', 'Affordable gaming entry point', 'Backlit keyboard'], cons: ['Gets hot quickly', 'Only 8GB RAM', 'Average build quality'], rating: 4.0, reviews_count: 5640 },
  { name: 'Acer Swift 3 SF314', category: 'Laptops', brand: 'Acer', price: 54999, description: 'AMD Ryzen 5 7530U, 16GB DDR4, compact everyday ultrabook with all-day battery.', specifications: { Processor: 'AMD Ryzen 5 7530U', RAM: '16GB DDR4', Storage: '512GB SSD', Display: '14" FHD IPS', Battery: '56Whr', Weight: '1.45 kg', OS: 'Windows 11 Home' }, pros: ['16GB RAM at this price', 'Lightweight and portable', 'Good battery life', 'Fast Ryzen 5 performance'], cons: ['Plasticky build', 'No backlit keyboard', 'Average display brightness'], rating: 4.2, reviews_count: 7823 },
  { name: 'MSI Raider GE78 HX', category: 'Laptops', brand: 'MSI', price: 249999, description: 'Intel Core i9-13980HX, RTX 4090, 64GB DDR5, 240Hz display. Desktop-class gaming performance.', specifications: { Processor: 'Intel Core i9-13980HX', RAM: '64GB DDR5', Storage: '2TB NVMe SSD', Display: '17.3" QHD 240Hz', GPU: 'NVIDIA RTX 4090 16GB', Battery: '99.9Whr', Weight: '3.1 kg' }, pros: ['Absolute best gaming performance', 'RTX 4090 laptop GPU', 'QHD 240Hz display', 'Extreme RAM capacity'], cons: ['Very heavy and bulky', 'Extremely expensive', 'Poor battery life', 'Loud fans'], rating: 4.4, reviews_count: 890 },
  { name: 'Apple MacBook Pro 14" M3 Pro', category: 'Laptops', brand: 'Apple', price: 199900, description: 'Apple M3 Pro with 11-core CPU, 18GB unified memory, mini-LED Liquid Retina XDR display.', specifications: { Processor: 'Apple M3 Pro 11-core', RAM: '18GB Unified Memory', Storage: '512GB SSD', Display: '14.2" Liquid Retina XDR', Battery: '18 hours', Weight: '1.61 kg', Ports: '3x Thunderbolt 4, HDMI, SD Card' }, pros: ['Exceptional M3 Pro performance', 'Best display quality', 'Long battery life', 'Premium build'], cons: ['Very expensive', 'Non-upgradeable RAM', 'macOS ecosystem lock-in'], rating: 4.9, reviews_count: 4320 },
  { name: 'Lenovo IdeaPad Slim 5', category: 'Laptops', brand: 'Lenovo', price: 44999, description: 'AMD Ryzen 5 7530U, 8GB RAM, everyday productivity laptop with good value for money.', specifications: { Processor: 'AMD Ryzen 5 7530U', RAM: '8GB DDR4', Storage: '512GB SSD', Display: '15.6" FHD IPS', Battery: '56Whr', Weight: '1.65 kg' }, pros: ['Good value for money', 'Ryzen 5 performance', 'Decent display', 'Expandable RAM'], cons: ['8GB base RAM', 'Average build quality', 'No backlit keyboard on base model'], rating: 4.1, reviews_count: 9450 },
  { name: 'ASUS VivoBook 16X', category: 'Laptops', brand: 'ASUS', price: 59999, description: 'Intel Core i5-12500H, 16GB DDR4, 1TB SSD, OLED display. Value OLED laptop for creators.', specifications: { Processor: 'Intel Core i5-12500H', RAM: '16GB DDR4', Storage: '1TB SSD', Display: '16" 2.5K OLED 120Hz', Battery: '70Whr', Weight: '1.88 kg' }, pros: ['OLED display at budget price', '16GB RAM', '1TB storage', 'Good build quality'], cons: ['Heavier than competitors', 'Fan noise under load', 'Glossy display fingerprint magnet'], rating: 4.3, reviews_count: 6780 },
  { name: 'HP Spectre x360 14', category: 'Laptops', brand: 'HP', price: 149999, description: 'Intel Core i7-1355U, 2-in-1 convertible with OLED display and HP pen included.', specifications: { Processor: 'Intel Core i7-1355U', RAM: '16GB LPDDR5', Storage: '512GB NVMe', Display: '13.5" 3:2 OLED Touch', Battery: '66Whr', Weight: '1.36 kg', Type: '2-in-1 Convertible' }, pros: ['Premium 2-in-1 design', '3:2 aspect ratio for productivity', 'OLED touchscreen', 'HP Pen included'], cons: ['Expensive', 'Iris Xe graphics limited for gaming', 'Shorter battery than rivals'], rating: 4.5, reviews_count: 2100 },
  { name: 'Lenovo Legion 5 Pro 2023', category: 'Laptops', brand: 'Lenovo', price: 119999, description: 'AMD Ryzen 7 7745HX, RTX 4060, 2K 165Hz display. Best mid-range gaming laptop.', specifications: { Processor: 'AMD Ryzen 7 7745HX', RAM: '16GB DDR5', Storage: '512GB NVMe', Display: '16" QHD 165Hz IPS', GPU: 'NVIDIA RTX 4060 8GB', Battery: '80Whr', Weight: '2.4 kg' }, pros: ['Excellent 2K display', 'Strong gaming performance', 'Good cooling system', 'MUX switch'], cons: ['Heavy', 'Mediocre battery life', 'Below-average speakers'], rating: 4.6, reviews_count: 3890 },
]

const smartphones: ProductInput[] = [
  { name: 'Apple iPhone 15 Pro Max', category: 'Smartphones', brand: 'Apple', price: 159900, description: 'A17 Pro chip, titanium design, 48MP camera system with 5x optical zoom, USB-C.', specifications: { Processor: 'A17 Pro', RAM: '8GB', Storage: '256GB', Display: '6.7" LTPO3 OLED 120Hz', Camera: '48MP + 12MP + 12MP', Battery: '4422mAh', '5G': 'Yes' }, pros: ['Best mobile processor', 'Excellent camera system', 'Titanium build', 'ProMotion 120Hz'], cons: ['Very expensive', 'No charger in box', 'Heavy', 'Limited customization'], rating: 4.8, reviews_count: 18920 },
  { name: 'Samsung Galaxy S24 Ultra', category: 'Smartphones', brand: 'Samsung', price: 134999, description: 'Snapdragon 8 Gen 3, 200MP camera, S Pen, 12GB RAM. Ultimate Android flagship.', specifications: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Display: '6.8" QHD+ LTPO AMOLED', Camera: '200MP + 12MP + 10MP + 10MP', Battery: '5000mAh', 'S Pen': 'Included' }, pros: ['200MP main camera', 'S Pen productivity', 'Stunning display', 'Best-in-class zoom'], cons: ['Very expensive', 'Camera app complex', 'Heavy at 232g'], rating: 4.7, reviews_count: 9876 },
  { name: 'OnePlus 12', category: 'Smartphones', brand: 'OnePlus', price: 64999, description: 'Snapdragon 8 Gen 3, Hasselblad camera, 100W charging, 50W wireless charging.', specifications: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Display: '6.82" QHD+ LTPO AMOLED 120Hz', Camera: '50MP + 48MP + 64MP', Battery: '5400mAh', Charging: '100W Wired + 50W Wireless' }, pros: ['Fastest charging at price', 'Great Hasselblad cameras', 'Smooth OxygenOS', 'Excellent value'], cons: ['No official IP rating', 'OxygenOS changes polarizing'], rating: 4.5, reviews_count: 7234 },
  { name: 'Xiaomi 14', category: 'Smartphones', brand: 'Xiaomi', price: 69999, description: 'Leica camera system, Snapdragon 8 Gen 3, compact flagship with exceptional photography.', specifications: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Display: '6.36" LTPO AMOLED 120Hz', Camera: '50MP Leica + 50MP + 50MP', Battery: '4610mAh', Charging: '90W Wired' }, pros: ['Leica optics quality', 'Compact flagship', 'Exceptional performance', 'Great display'], cons: ['MIUI ads in stock apps', 'Average battery size', 'Premium price'], rating: 4.4, reviews_count: 4560 },
  { name: 'OPPO Find X7 Ultra', category: 'Smartphones', brand: 'OPPO', price: 99999, description: 'Dual periscope cameras, Hasselblad tuning, Dimensity 9300, best camera smartphone.', specifications: { Processor: 'MediaTek Dimensity 9300', RAM: '16GB', Storage: '512GB', Display: '6.82" LTPO3 AMOLED 120Hz', Camera: '50MP Hasselblad + 50MP + 50MP + 50MP', Battery: '5000mAh', Charging: '100W Wired' }, pros: ['Unmatched camera versatility', 'Dual periscope telephoto', 'Large battery', 'Premium design'], cons: ['Limited India availability', 'Software updates less frequent'], rating: 4.6, reviews_count: 1230 },
  { name: 'Samsung Galaxy A54 5G', category: 'Smartphones', brand: 'Samsung', price: 29999, description: 'Exynos 1380, IP67 rated, 50MP OIS camera, 5000mAh battery. Best mid-ranger.', specifications: { Processor: 'Exynos 1380', RAM: '8GB', Storage: '128GB', Display: '6.4" FHD+ Super AMOLED', Camera: '50MP OIS + 12MP + 5MP', Battery: '5000mAh', 'Water Resistance': 'IP67' }, pros: ['Official IP67 rating', '3 years Android updates', 'Bright AMOLED display', 'OIS on main camera'], cons: ['Average Exynos performance', 'No 90Hz display', 'Slow 25W charging'], rating: 4.3, reviews_count: 15670 },
  { name: 'Realme GT 5 Pro', category: 'Smartphones', brand: 'Realme', price: 39999, description: 'Snapdragon 8 Gen 3, periscope camera, 240W charging. Fastest-charging phone available.', specifications: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Display: '6.78" LTPO2 AMOLED 144Hz', Camera: '50MP + 50MP Periscope + 8MP', Battery: '5400mAh', Charging: '240W Wired' }, pros: ['240W insane charging speed', 'Snapdragon 8 Gen 3 performance', '144Hz display', 'Periscope camera'], cons: ['Camera software needs work', 'Build feels premium-plastic'], rating: 4.4, reviews_count: 6780 },
  { name: 'Redmi Note 13 Pro+ 5G', category: 'Smartphones', brand: 'Xiaomi', price: 29999, description: 'Dimensity 7200 Ultra, 200MP camera, IP68 waterproofing, 120W charging. Best budget camera.', specifications: { Processor: 'Dimensity 7200 Ultra', RAM: '12GB', Storage: '256GB', Display: '6.67" AMOLED 120Hz', Camera: '200MP + 8MP + 2MP', Battery: '5000mAh', 'Water Resistance': 'IP68' }, pros: ['200MP camera at mid-range', 'IP68 waterproofing', '120W fast charging', 'Premium design'], cons: ['Dimensity 7200 not top-tier', 'MIUI ads', 'No wireless charging'], rating: 4.3, reviews_count: 11230 },
  { name: 'Apple iPhone 15', category: 'Smartphones', brand: 'Apple', price: 79900, description: 'A16 Bionic chip, 48MP main camera, Dynamic Island, USB-C. Entry-level iPhone 15.', specifications: { Processor: 'A16 Bionic', RAM: '6GB', Storage: '128GB', Display: '6.1" OLED Super Retina XDR', Camera: '48MP + 12MP', Battery: '3349mAh', Charging: 'USB-C' }, pros: ['A16 Bionic powerful chip', 'Excellent camera quality', 'Compact size', 'Dynamic Island'], cons: ['60Hz display', 'No 5G millimeter wave', 'Base 128GB storage'], rating: 4.6, reviews_count: 22340 },
  { name: 'Vivo V30 Pro 5G', category: 'Smartphones', brand: 'Vivo', price: 39999, description: 'Dimensity 8200, Aura Light portrait system, curved AMOLED, 50W wireless charging.', specifications: { Processor: 'Dimensity 8200', RAM: '12GB', Storage: '256GB', Display: '6.78" Curved AMOLED 120Hz', Camera: '50MP + 50MP + 12MP', Battery: '5000mAh', Charging: '80W Wired + 50W Wireless' }, pros: ['Aura light for portraits', 'Wireless charging at price', 'Curved premium display', 'Consistent camera'], cons: ['FunTouch OS heavy', 'Limited update promises', 'Average gaming performance'], rating: 4.2, reviews_count: 3450 },
]

const headphones: ProductInput[] = [
  { name: 'Sony WH-1000XM5', category: 'Headphones', brand: 'Sony', price: 29990, description: 'Industry-leading noise cancellation, 30-hour battery, premium sound. Best ANC headphones.', specifications: { Type: 'Over-Ear', ANC: 'Yes - Industry Leading', Battery: '30 hours', Driver: '30mm', Connectivity: 'Bluetooth 5.2', Microphone: 'Built-in + AI', Weight: '250g' }, pros: ['Best-in-class ANC', 'Excellent audio quality', 'Long battery life', 'Comfortable for long use'], cons: ['Expensive', 'Cannot fold flat', 'Touch controls can misfire'], rating: 4.7, reviews_count: 23450 },
  { name: 'Bose QuietComfort 45', category: 'Headphones', brand: 'Bose', price: 24990, description: 'Legendary Bose noise cancellation, 24-hour battery, comfortable ear cushions for all-day use.', specifications: { Type: 'Over-Ear', ANC: 'Yes - Bose Acoustic NC', Battery: '24 hours', Connectivity: 'Bluetooth 5.1', Foldable: 'Yes', Weight: '238g', Modes: 'Quiet/Aware' }, pros: ['Excellent noise cancellation', 'Very comfortable', 'Good call quality', 'Awareness mode'], cons: ['Average soundstage', 'No LDAC/aptX', 'Touch controls limited'], rating: 4.5, reviews_count: 11230 },
  { name: 'Apple AirPods Max', category: 'Headphones', brand: 'Apple', price: 59900, description: 'Apple H1 chip in each ear cup, Adaptive EQ, computational audio. Best for Apple ecosystem.', specifications: { Type: 'Over-Ear', ANC: 'Active Noise Cancellation', Driver: '40mm', Connectivity: 'Bluetooth 5.0', Battery: '20 hours', Charging: 'Lightning', Weight: '385g' }, pros: ['Best Apple ecosystem integration', 'Superb build quality', 'Excellent audio with Spatial Audio', 'Premium materials'], cons: ['Very expensive', 'Heavy at 385g', 'Lightning charging (old)', 'No foldable design'], rating: 4.4, reviews_count: 5670 },
  { name: 'Sennheiser Momentum 4', category: 'Headphones', brand: 'Sennheiser', price: 29990, description: 'Audiophile sound signature, 60-hour battery, ANC, premium build. For audiophiles on the go.', specifications: { Type: 'Over-Ear', ANC: 'Hybrid ANC', Battery: '60 hours', Driver: '42mm', Connectivity: 'Bluetooth 5.2', Codecs: 'aptX Adaptive, LDAC, AAC', Weight: '293g' }, pros: ['60-hour battery class-leading', 'Audiophile sound quality', 'LDAC support', 'Premium build'], cons: ['Bulky design', 'ANC not as strong as Sony/Bose', 'Expensive'], rating: 4.5, reviews_count: 4320 },
  { name: 'JBL Tune 770NC', category: 'Headphones', brand: 'JBL', price: 6999, description: 'Budget ANC headphones with 70-hour battery and JBL Signature sound. Best value ANC.', specifications: { Type: 'Over-Ear', ANC: 'Adaptive ANC', Battery: '70 hours', Connectivity: 'Bluetooth 5.3', Foldable: 'Yes', Modes: 'ANC/Ambient/Off', Weight: '220g' }, pros: ['70-hour amazing battery', 'ANC at budget price', 'Lightweight', 'JBL Headphones app'], cons: ['Average build quality', 'Plasticky feel', 'Basic call quality'], rating: 4.1, reviews_count: 18760 },
  { name: 'boAt Rockerz 550', category: 'Headphones', brand: 'boAt', price: 1299, description: 'Budget over-ear headphone with 20-hour battery and boAt signature bass. Great for budget buyers.', specifications: { Type: 'Over-Ear', Battery: '20 hours', Driver: '50mm', Connectivity: 'Bluetooth 5.0', Microphone: 'Yes', Foldable: 'Yes', Weight: '180g' }, pros: ['Very affordable', 'Good bass response', 'Foldable design', 'Decent battery'], cons: ['No ANC', 'Average build quality', 'Mediocre call quality', 'Basic sound signature'], rating: 3.9, reviews_count: 89430 },
  { name: 'Sony WF-1000XM5', category: 'Headphones', brand: 'Sony', price: 19990, description: 'Best TWS earbuds with industry-leading ANC, LDAC support, 36-hour total battery.', specifications: { Type: 'In-Ear TWS', ANC: 'Industry-leading ANC', Battery: '8hr+28hr case', Codecs: 'LDAC, aptX, AAC', Connectivity: 'Bluetooth 5.3', IPX4: 'Yes', Weight: '5.9g each' }, pros: ['Best ANC in TWS', 'Exceptional audio quality', 'LDAC hi-res audio', 'Comfortable fit'], cons: ['Expensive for earbuds', 'Bulky case', 'Touch controls complex'], rating: 4.7, reviews_count: 15230 },
  { name: 'Samsung Galaxy Buds2 Pro', category: 'Headphones', brand: 'Samsung', price: 12999, description: 'Hi-Fi 24-bit audio, intelligent ANC, 360 Audio, seamless Galaxy ecosystem integration.', specifications: { Type: 'In-Ear TWS', ANC: 'Intelligent ANC', Battery: '5hr+13hr case', Codecs: '24-bit audio, AAC', Connectivity: 'Bluetooth 5.3', IPX7: 'Yes', Weight: '5.5g each' }, pros: ['24-bit hi-fi audio', 'Excellent ANC', 'Compact case', 'Galaxy integration'], cons: ['Best features limited to Samsung phones', 'Average battery life', 'Small wing tips'], rating: 4.3, reviews_count: 7890 },
  { name: 'OneOdio A10 Gaming Headset', category: 'Headphones', brand: 'OneOdio', price: 2499, description: 'Budget gaming headset with detachable microphone, 50mm drivers, strong bass for gaming.', specifications: { Type: 'Over-Ear Gaming', Driver: '50mm', Connectivity: 'Wired 3.5mm + USB', Microphone: 'Detachable Boom', Frequency: '20Hz-20kHz', Impedance: '32Ω', Weight: '295g' }, pros: ['Budget gaming option', 'Detachable mic', 'Strong bass', 'Multi-platform compatible'], cons: ['Wired only', 'Average sound quality', 'Plasticky build'], rating: 3.8, reviews_count: 34560 },
  { name: 'Audio-Technica ATH-M50x', category: 'Headphones', brand: 'Audio-Technica', price: 14990, description: 'Professional studio monitor headphones with exceptional audio accuracy. Industry standard.', specifications: { Type: 'Over-Ear Studio', Driver: '45mm', Impedance: '38Ω', Frequency: '15Hz-28kHz', Connectivity: 'Wired 3.5mm + 6.3mm', Foldable: 'Yes', Weight: '285g' }, pros: ['Reference-quality audio', 'Excellent detail retrieval', 'Professional studio standard', 'Detachable cable'], cons: ['No wireless', 'No ANC', 'Clamping force high initially'], rating: 4.6, reviews_count: 28900 },
]

const tablets: ProductInput[] = [
  { name: 'Apple iPad Pro 12.9" M2', category: 'Tablets', brand: 'Apple', price: 112900, description: 'M2 chip, Liquid Retina XDR ProMotion display, USB4/Thunderbolt, Face ID.', specifications: { Processor: 'Apple M2', RAM: '8GB', Storage: '128GB', Display: '12.9" Liquid Retina XDR', Connectivity: 'WiFi 6E + 5G (cellular)', Battery: '10hr', 'Apple Pencil': 'Gen 2 compatible' }, pros: ['Best tablet display ever', 'Desktop-class M2 performance', 'Thunderbolt connectivity', 'Pro level apps'], cons: ['Very expensive', 'iPadOS limitations vs desktop', 'Accessories sold separately'], rating: 4.8, reviews_count: 8920 },
  { name: 'Samsung Galaxy Tab S9+', category: 'Tablets', brand: 'Samsung', price: 89999, description: 'Snapdragon 8 Gen 2, Dynamic AMOLED 2X, IP68, S Pen included. Best Android tablet.', specifications: { Processor: 'Snapdragon 8 Gen 2', RAM: '12GB', Storage: '256GB', Display: '12.4" Dynamic AMOLED 2X 120Hz', 'Water Resistance': 'IP68', 'S Pen': 'Included', Battery: '10090mAh' }, pros: ['Included S Pen', 'Excellent AMOLED display', 'IP68 waterproof', 'DeX desktop mode'], cons: ['Expensive', 'Android tablet app ecosystem limited', 'Heavy at 581g'], rating: 4.6, reviews_count: 4560 },
  { name: 'Apple iPad Air 5th Gen', category: 'Tablets', brand: 'Apple', price: 59900, description: 'Apple M1 chip, 10.9" Liquid Retina, USB-C, 5G. Best value iPad for most users.', specifications: { Processor: 'Apple M1', RAM: '8GB', Storage: '64GB', Display: '10.9" Liquid Retina', Connectivity: 'WiFi 6 + 5G', Battery: '10hr', 'Pencil': 'Gen 2 compatible' }, pros: ['M1 chip extremely fast', 'Light and thin', 'USB-C charging', 'Good display quality'], cons: ['64GB base storage too low', 'Bezels larger than Pro', 'Average camera'], rating: 4.7, reviews_count: 12340 },
  { name: 'Lenovo Tab P11 Pro Gen 2', category: 'Tablets', brand: 'Lenovo', price: 36999, description: 'MediaTek Kompanio 1300T, 11.2" OLED display, keyboard included, productivity tablet.', specifications: { Processor: 'MediaTek Kompanio 1300T', RAM: '6GB', Storage: '128GB', Display: '11.2" 2.5K OLED 120Hz', Battery: '8600mAh', Connectivity: 'WiFi 6', Accessories: 'Keyboard + Pen included' }, pros: ['OLED display at mid-range', 'Keyboard included in box', 'Stylus included', 'Good value bundle'], cons: ['MediaTek performance inconsistent', 'Android tablet limitations', 'Build feels plasticky'], rating: 4.0, reviews_count: 3450 },
  { name: 'Samsung Galaxy Tab A8', category: 'Tablets', brand: 'Samsung', price: 19999, description: 'Unisoc Tiger T618, 10.5" LCD, 7040mAh battery. Budget family and entertainment tablet.', specifications: { Processor: 'Unisoc Tiger T618', RAM: '4GB', Storage: '64GB', Display: '10.5" LCD FHD+', Battery: '7040mAh', Connectivity: 'WiFi 5', Ports: 'USB-C, microSD' }, pros: ['Affordable price', 'Decent screen size', 'Good battery life', 'Lightweight'], cons: ['Underpowered processor', 'LCD not AMOLED', 'Slow software updates'], rating: 3.9, reviews_count: 25670 },
  { name: 'Apple iPad Mini 6th Gen', category: 'Tablets', brand: 'Apple', price: 46900, description: 'Apple A15 Bionic, 8.3" Liquid Retina, Touch ID on side button, USB-C, 5G. Best compact tablet.', specifications: { Processor: 'Apple A15 Bionic', RAM: '4GB', Storage: '64GB', Display: '8.3" Liquid Retina', Connectivity: 'WiFi 6 + 5G', Battery: '9hr', 'Pencil': 'Gen 2 compatible' }, pros: ['Ultra compact and portable', 'Excellent A15 performance', 'Touch ID side button unique', 'USB-C connectivity'], cons: ['Jelly scroll display issue', '64GB base storage', 'No headphone jack'], rating: 4.5, reviews_count: 9870 },
  { name: 'OnePlus Pad', category: 'Tablets', brand: 'OnePlus', price: 37999, description: 'MediaTek Dimensity 9000, 11.61" 144Hz LCD, 9510mAh, 67W charging. Best Android tablet value.', specifications: { Processor: 'MediaTek Dimensity 9000', RAM: '8GB', Storage: '128GB', Display: '11.61" 144Hz IPS LCD', Battery: '9510mAh', Charging: '67W Wired', Connectivity: 'WiFi 6' }, pros: ['144Hz display at price', 'Large battery with 67W charging', 'Strong Dimensity 9000 SoC', 'Premium aluminum design'], cons: ['No 5G support', 'Limited app optimization for large screen', 'Single speaker'], rating: 4.3, reviews_count: 5670 },
  { name: 'Xiaomi Pad 6', category: 'Tablets', brand: 'Xiaomi', price: 26999, description: 'Snapdragon 870, 11" 144Hz display, quad speakers, 8840mAh battery. Best budget performance tablet.', specifications: { Processor: 'Snapdragon 870', RAM: '6GB', Storage: '128GB', Display: '11" 144Hz IPS LCD 2.8K', Battery: '8840mAh', Charging: '33W Wired', Connectivity: 'WiFi 6' }, pros: ['2.8K 144Hz display outstanding', 'Quad speaker setup', 'Fast Snapdragon 870', 'Budget-friendly price'], cons: ['MIUI for Pad has ads', 'No pen support in base package', 'Aluminium only on Pro version'], rating: 4.4, reviews_count: 14230 },
  { name: 'OPPO Pad 2', category: 'Tablets', brand: 'OPPO', price: 34999, description: 'MediaTek Dimensity 9000, 11.61" 144Hz display, 9510mAh, excellent multitasking.', specifications: { Processor: 'MediaTek Dimensity 9000', RAM: '8GB', Storage: '256GB', Display: '11.61" 144Hz LCD', Battery: '9510mAh', Charging: '67W', Connectivity: 'WiFi 6' }, pros: ['256GB storage at price', 'Smooth 144Hz display', 'Good multitasking software', 'Premium build quality'], cons: ['ColorOS can be cluttered', 'No Google certification initially', 'Limited accessory ecosystem'], rating: 4.2, reviews_count: 3210 },
  { name: 'Samsung Galaxy Tab S9 FE', category: 'Tablets', brand: 'Samsung', price: 44999, description: 'Exynos 1380, 10.9" TFT display, IP68, S Pen included, Samsung ecosystem integration.', specifications: { Processor: 'Exynos 1380', RAM: '6GB', Storage: '128GB', Display: '10.9" FHD+ TFT 90Hz', Battery: '8000mAh', 'Water Resistance': 'IP68', 'S Pen': 'Included' }, pros: ['IP68 water resistance', 'S Pen included', 'Samsung ecosystem support', 'Durable build'], cons: ['TFT not AMOLED', '90Hz is not 120Hz', 'Exynos 1380 mid-tier performance'], rating: 4.1, reviews_count: 7890 },
]

const smartwatches: ProductInput[] = [
  { name: 'Apple Watch Series 9 GPS+Cellular', category: 'Smartwatches', brand: 'Apple', price: 62900, description: 'S9 chip, Double Tap gesture, 18hr battery, ECG, blood oxygen, always-on display.', specifications: { Processor: 'S9 SiP', Display: '41mm Always-On Retina LTPO', 'Health Sensors': 'ECG, Blood Oxygen, Heart Rate', Connectivity: 'Bluetooth 5.3, WiFi, LTE', Battery: '18 hours', 'Water Resistance': '50m', OS: 'watchOS 10' }, pros: ['Best health monitoring', 'Double Tap new feature', 'Excellent app ecosystem', 'Apple ecosystem integration'], cons: ['Only 18-hour battery', 'Only works with iPhone', 'Expensive'], rating: 4.7, reviews_count: 14560 },
  { name: 'Samsung Galaxy Watch 6 Classic', category: 'Smartwatches', brand: 'Samsung', price: 39999, description: 'Rotating bezel returns, Exynos W930, advanced health sensors, Wear OS 4. Best Android watch.', specifications: { Processor: 'Exynos W930', Display: '47mm AMOLED', 'Health Sensors': 'BioActive (ECG, Blood Pressure, SpO2)', Connectivity: 'Bluetooth 5.3, WiFi, LTE', Battery: '40 hours', 'Water Resistance': '5ATM/IP68', OS: 'Wear OS 4' }, pros: ['Classic rotating bezel', 'Blood pressure monitoring', 'Wear OS ecosystem', 'Longer battery than Apple'], cons: ['Works best with Samsung phones', 'Heavy 52g case', 'Expensive'], rating: 4.4, reviews_count: 6780 },
  { name: 'Garmin Forerunner 265', category: 'Smartwatches', brand: 'Garmin', price: 44999, description: 'AMOLED display on a running watch, advanced training metrics, HRV status, 13-day battery.', specifications: { Display: '46mm AMOLED', 'Battery (Smartwatch)': '13 days', 'Battery (GPS)': '20 hours', 'Health Sensors': 'HR, SpO2, HRV, Stress', GPS: 'Multi-band', 'Water Resistance': '5ATM', 'Running Metrics': 'VO2 Max, Training Load' }, pros: ['Best running metrics', '13-day battery', 'AMOLED display', 'Multi-band GPS accuracy'], cons: ['Expensive for sports watch', 'Limited smartwatch features vs Apple/Samsung', 'Interface not as smooth'], rating: 4.6, reviews_count: 3450 },
  { name: 'Noise ColorFit Pro 4', category: 'Smartwatches', brand: 'Noise', price: 2499, description: 'Budget Indian smartwatch with 1.78" AMOLED, 7-day battery, 100+ sports modes.', specifications: { Display: '1.78" AMOLED', Battery: '7 days', 'Health Sensors': 'SpO2, HR, Stress', Connectivity: 'Bluetooth 5.0', 'Water Resistance': 'IP68', 'Sports Modes': '100+', Strap: 'Silicone' }, pros: ['Very affordable', 'AMOLED display', '7-day battery', 'Good for casual tracking'], cons: ['Limited app ecosystem', 'No LTE', 'Inaccurate health sensors'], rating: 3.8, reviews_count: 67890 },
  { name: 'Fitbit Charge 6', category: 'Smartwatches', brand: 'Fitbit', price: 14999, description: 'Google integration, ECG, EDA sensor, 7-day battery. Best for health and fitness tracking.', specifications: { Display: 'AMOLED', Battery: '7 days', 'Health Sensors': 'ECG, EDA, SpO2, HR', Connectivity: 'Bluetooth, WiFi, NFC', 'Water Resistance': '5ATM', 'Google Integration': 'Maps, Wallet, YT Music', GPS: 'Built-in' }, pros: ['Google Maps on wrist', 'NFC payments', 'ECG and EDA sensors', '7-day battery'], cons: ['No touchscreen response in cold', 'Small display', 'Fitbit app changing to Google'], rating: 4.2, reviews_count: 8930 },
  { name: 'Garmin Venu 3', category: 'Smartwatches', brand: 'Garmin', price: 49999, description: 'AMOLED health smartwatch, sleep coaching, wheelchair mode, Garmin Pay, 14-day battery.', specifications: { Display: '45mm AMOLED', Battery: '14 days', 'Health Sensors': 'ECG, SpO2, HRV, Skin Temp', Connectivity: 'Bluetooth 5.0, WiFi, NFC', 'Water Resistance': '5ATM', GPS: 'Built-in', OS: 'Garmin OS' }, pros: ['14-day battery for AMOLED', 'Best sleep tracking', 'Garmin Pay NFC', 'Wheelchair fitness mode'], cons: ['Expensive', 'Limited third-party apps', 'Not as polished as Apple/Samsung UI'], rating: 4.5, reviews_count: 2340 },
  { name: 'boAt Wave Sigma', category: 'Smartwatches', brand: 'boAt', price: 1799, description: 'Budget smartwatch with 1.85" display, 10-day battery, BT calling, 100+ sports modes.', specifications: { Display: '1.85" TFT LCD', Battery: '10 days', 'Health Sensors': 'SpO2, HR, Stress', Connectivity: 'Bluetooth 5.3', 'Water Resistance': 'IP67', 'Sports Modes': '100+', Calling: 'Bluetooth Calling' }, pros: ['Extremely affordable', 'Large display', 'BT calling feature', 'Good battery life'], cons: ['TFT not AMOLED', 'Basic health sensors', 'Plastic build quality', 'No GPS'], rating: 3.7, reviews_count: 45670 },
  { name: 'Amazfit GTR 4', category: 'Smartwatches', brand: 'Amazfit', price: 14999, description: 'Alexa built-in, dual-band GPS, 150+ sports modes, 14-day battery, AMOLED display.', specifications: { Display: '46mm AMOLED', Battery: '14 days', 'Health Sensors': 'HR, SpO2, Stress, Body Battery', Connectivity: 'Bluetooth 5.0, WiFi', 'Water Resistance': '5ATM', GPS: 'Dual-band GPS', Alexa: 'Built-in' }, pros: ['Alexa voice assistant', 'Dual-band GPS accuracy', '14-day battery', 'AMOLED display at price'], cons: ['Zepp OS limited apps', 'Health data less accurate vs Garmin', 'No 4G LTE'], rating: 4.3, reviews_count: 12340 },
  { name: 'Samsung Galaxy Watch 6 44mm', category: 'Smartwatches', brand: 'Samsung', price: 29999, description: 'Exynos W930, 44mm AMOLED, advanced sleep coaching, body composition analysis.', specifications: { Processor: 'Exynos W930', Display: '44mm AMOLED', 'Health Sensors': 'BioActive Sensor, ECG, SpO2', Connectivity: 'Bluetooth 5.3, WiFi, LTE', Battery: '44 hours', 'Water Resistance': '5ATM/IP68', OS: 'Wear OS 4' }, pros: ['Body composition analysis unique', 'Google ecosystem access', 'Good battery life vs Series 9', 'AMOLED display'], cons: ['No rotating bezel', 'Fewer Galaxy apps than Classic', 'Works best with Samsung phones'], rating: 4.3, reviews_count: 9870 },
  { name: 'Fire-Boltt Phoenix Ultra', category: 'Smartwatches', brand: 'Fire-Boltt', price: 3499, description: 'AMOLED display, Bluetooth calling, 123 sports modes, 7-day battery, budget smartwatch.', specifications: { Display: '1.43" AMOLED', Battery: '7 days', 'Health Sensors': 'SpO2, HR, Stress', Connectivity: 'Bluetooth 5.2', 'Water Resistance': 'IP67', 'Sports Modes': '123', Calling: 'Bluetooth Calling' }, pros: ['AMOLED at very low price', 'BT calling feature', 'Comprehensive sports tracking', 'Good display brightness'], cons: ['Health sensor accuracy limited', 'No built-in GPS', 'Plasticky build'], rating: 3.9, reviews_count: 34560 },
]

const cameras: ProductInput[] = [
  { name: 'Sony Alpha 7 IV', category: 'Cameras', brand: 'Sony', price: 259990, description: 'Full-frame 33MP BSI CMOS sensor, 10fps burst, 4K 60fps video, hybrid autofocus. Pro hybrid camera.', specifications: { Sensor: '33MP Full-Frame BSI CMOS', AF: '759 Phase-detect points', Video: '4K 60fps 10-bit', Burst: '10fps', ISO: '100-51200', Stabilization: '5.5-stop IBIS', Battery: 'NP-FZ100' }, pros: ['Exceptional video quality', 'Best-in-class autofocus', 'Full-frame sensor', 'Professional hybrid'], cons: ['Very expensive body only', 'APS-C crop at 4K60', 'Large and heavy'], rating: 4.8, reviews_count: 5670 },
  { name: 'Canon EOS R50', category: 'Cameras', brand: 'Canon', price: 74990, description: '24.2MP APS-C, DIGIC X processor, Dual Pixel CMOS AF, 4K video. Best entry mirrorless.', specifications: { Sensor: '24.2MP APS-C CMOS', AF: 'Dual Pixel CMOS AF II', Video: '4K 30fps', Burst: '15fps electronic', ISO: '100-32000', Weight: '375g', Connectivity: 'WiFi, Bluetooth' }, pros: ['Excellent Dual Pixel AF', 'Compact and lightweight', 'Good 4K video', 'Entry-level price'], cons: ['Crop in 4K mode', 'Single card slot', 'Battery life average'], rating: 4.5, reviews_count: 4560 },
  { name: 'Nikon Z50 II', category: 'Cameras', brand: 'Nikon', price: 89990, description: '20.9MP APS-C Z-mount, Expeed 7, 30fps burst, vertical grip compatible. Content creator camera.', specifications: { Sensor: '20.9MP APS-C CMOS', Processor: 'Expeed 7', AF: '285 Phase-detect points', Video: '4K 30fps', Burst: '30fps electronic', ISO: '100-51200', Weight: '390g' }, pros: ['30fps burst rate', 'Expeed 7 fast processor', 'Excellent subject tracking', 'Z-mount lens selection'], cons: ['No IBIS', 'Limited 4K specs vs rivals', 'No worm-gear tilt screen'], rating: 4.4, reviews_count: 2340 },
  { name: 'Fujifilm X-T5', category: 'Cameras', brand: 'Fujifilm', price: 164990, description: '40.2MP X-Trans BSI CMOS 5 HR sensor, 7-stop IBIS, 4K 60fps, film simulations. For photographers.', specifications: { Sensor: '40.2MP X-Trans BSI CMOS 5', Stabilization: '7-stop IBIS', Video: '4K 60fps', Burst: '15fps mechanical', 'Film Simulations': '20 modes', AF: 'Phase + Contrast Detect', Weight: '557g' }, pros: ['40MP outstanding resolution', 'Excellent IBIS', 'Fujifilm film simulations', 'Compact for resolution'], cons: ['Complex menu system', 'No vertical crop 4K60', 'Rear wheel wobbles'], rating: 4.7, reviews_count: 3450 },
  { name: 'GoPro Hero 12 Black', category: 'Cameras', brand: 'GoPro', price: 34990, description: '5.3K video, HyperSmooth 6.0, waterproof to 10m without housing, enduro battery.', specifications: { Video: '5.3K 60fps', Stabilization: 'HyperSmooth 6.0', 'Water Resistance': '10m', Battery: '1720mAh Enduro', Connectivity: 'Bluetooth 5.0, WiFi', Display: '2.27" rear LCD', Weight: '154g' }, pros: ['Best action stabilization', 'Compact and rugged', 'Excellent video quality', 'Easy to use'], cons: ['Battery life low', 'Limited in low light', 'Accessories expensive'], rating: 4.4, reviews_count: 12340 },
  { name: 'Sony ZV-E10', category: 'Cameras', brand: 'Sony', price: 59990, description: '24.2MP APS-C, directional 3-capsule mic, 4K video, vari-angle touchscreen. Best vlogging camera.', specifications: { Sensor: '24.2MP APS-C CMOS', Microphone: '3-Capsule Directional Mic', Video: '4K 30fps', AF: '425 Phase-detect points', Display: 'Vari-angle touchscreen', Weight: '343g', Mount: 'Sony E-mount' }, pros: ['Excellent vlogging microphone', 'Vari-angle screen for selfies', 'Compact and affordable', 'E-mount lens ecosystem'], cons: ['No IBIS', 'Battery life short', '4K has rolling shutter'], rating: 4.4, reviews_count: 8760 },
  { name: 'Panasonic Lumix G100', category: 'Cameras', brand: 'Panasonic', price: 52990, description: '20.3MP Micro Four Thirds, 3-mic audio with wind noise cancellation, 4K video, lightweight vlog camera.', specifications: { Sensor: '20.3MP MFT', Microphone: '3-Mic array with wind noise cancellation', Video: '4K 30fps', Stabilization: 'Dual IS2', Weight: '347g', Display: 'Fully articulating touch', Mount: 'Micro Four Thirds' }, pros: ['Outstanding audio quality for vlogging', 'Articulating touchscreen', 'Very lightweight', 'Excellent image stabilization'], cons: ['No DFD AF less accurate vs rivals', 'MFT has crop disadvantage', 'No weather sealing'], rating: 4.2, reviews_count: 4320 },
  { name: 'Canon EOS R8', category: 'Cameras', brand: 'Canon', price: 134990, description: 'Full-frame 24.2MP, DIGIC X, Dual Pixel CMOS AF II, 4K 60fps uncropped. Budget full-frame.', specifications: { Sensor: '24.2MP Full-Frame CMOS', AF: 'Dual Pixel CMOS AF II', Video: '4K 60fps uncropped', Burst: '40fps electronic', ISO: '100-102400', Weight: '461g', Battery: 'LP-E17' }, pros: ['Full-frame at accessible price', '4K 60fps uncropped', 'Excellent Dual Pixel AF', 'Lightweight for full-frame'], cons: ['Single card slot', 'No IBIS', 'Small battery'], rating: 4.5, reviews_count: 5670 },
  { name: 'DJI Osmo Pocket 3', category: 'Cameras', brand: 'DJI', price: 44990, description: '1" CMOS sensor, 3-axis gimbal, 4K 120fps, 2" touchscreen. Best gimbal camera for creators.', specifications: { Sensor: '1" CMOS', Stabilization: '3-axis gimbal', Video: '4K 120fps', Display: '2" OLED touchscreen', Battery: '1300mAh', Connectivity: 'WiFi, Bluetooth', Weight: '179g' }, pros: ['Built-in 3-axis gimbal', 'Silky smooth stabilization', 'Large 1" sensor', '4K 120fps slow motion'], cons: ['Not waterproof without housing', 'Short battery life', 'Fixed focal length'], rating: 4.6, reviews_count: 9870 },
  { name: 'Sony ZV-1 II', category: 'Cameras', brand: 'Sony', price: 69990, description: '20.1MP 1" sensor, ultra-wide 18mm equivalent, built-in ND filter, 4K vlogging. Compact powerhouse.', specifications: { Sensor: '20.1MP 1" CMOS', Lens: '18-50mm equivalent', Video: '4K 30fps', 'ND Filter': 'Built-in 3-stop', Microphone: 'Directional 3-capsule', Display: 'Vari-angle', Weight: '292g' }, pros: ['Ultra-wide 18mm great for vlogging', 'Built-in ND filter', 'Compact and pocketable', 'Excellent Sony autofocus'], cons: ['Short zoom range', '4K 30fps only', 'Limited low light vs bigger sensors'], rating: 4.3, reviews_count: 6780 },
]

const monitors: ProductInput[] = [
  { name: 'LG 27GP850-B UltraGear', category: 'Monitors', brand: 'LG', price: 34999, description: '27" QHD 165Hz Nano IPS, 1ms GTG, NVIDIA G-Sync compatible, HDMI 2.0, DisplayPort 1.4.', specifications: { Display: '27" QHD 2560x1440', Panel: 'Nano IPS', 'Refresh Rate': '165Hz', 'Response Time': '1ms GTG', HDR: 'VESA DisplayHDR 400', 'Sync Tech': 'G-Sync Compatible / FreeSync', Ports: 'HDMI 2.0 x2, DP 1.4' }, pros: ['Excellent 165Hz for gaming', 'Accurate Nano IPS colors', '1ms response time', 'Good for gaming and content'], cons: ['Thin stand wobbles', 'Basic HDR400 only', 'Average contrast ratio'], rating: 4.5, reviews_count: 9870 },
  { name: 'Samsung 32" Odyssey G7 QLED', category: 'Monitors', brand: 'Samsung', price: 54999, description: '32" 4K 144Hz VA QLED, 1000R curvature, 1ms, DisplayHDR 600. Immersive gaming display.', specifications: { Display: '32" 4K 3840x2160', Panel: 'VA QLED', 'Refresh Rate': '144Hz', 'Response Time': '1ms', HDR: 'VESA DisplayHDR 600', Curvature: '1000R', Ports: 'HDMI 2.1 x2, DP 1.4' }, pros: ['4K 144Hz excellent combo', 'HDMI 2.1 for consoles', 'Samsung QLED vibrant colors', 'HDR600 good brightness'], cons: ['VA panel glow', 'Heavy', 'Expensive', 'Some backlight bloom in HDR'], rating: 4.4, reviews_count: 4560 },
  { name: 'ASUS ProArt PA278CV', category: 'Monitors', brand: 'ASUS', price: 39999, description: '27" QHD IPS, 100% sRGB 100% Rec.709, factory calibrated, USB-C 90W, perfect for creators.', specifications: { Display: '27" QHD 2560x1440', Panel: 'IPS', 'Color Accuracy': 'Delta E < 2', 'Color Space': '100% sRGB, 100% Rec.709', Calibration: 'Factory', 'USB-C': '90W Power Delivery', Ports: 'HDMI 2.0, DP 1.2, USB-C, USB-A hub' }, pros: ['Factory calibrated color accuracy', '100% sRGB accurate', 'USB-C 90W charging', 'Great for design work'], cons: ['60Hz only', 'No HDR worth mentioning', 'Not a gaming monitor'], rating: 4.6, reviews_count: 5670 },
  { name: 'Dell S2722DGM', category: 'Monitors', brand: 'Dell', price: 24999, description: '27" QHD 165Hz VA, AMD FreeSync Premium, 1ms MPRT. Budget gaming monitor with good specs.', specifications: { Display: '27" QHD 2560x1440', Panel: 'VA', 'Refresh Rate': '165Hz', 'Response Time': '1ms MPRT', HDR: 'VESA DisplayHDR 400', 'Sync Tech': 'FreeSync Premium', Ports: 'HDMI 1.4, DP 1.2' }, pros: ['165Hz at budget', 'VA panel deep blacks', 'Good size for price', 'Dell build quality'], cons: ['No USB hub', 'Basic HDMI 1.4', 'HDR400 basic', 'VA ghosting in fast scenes'], rating: 4.2, reviews_count: 12340 },
  { name: 'BenQ PD2705U', category: 'Monitors', brand: 'BenQ', price: 64999, description: '27" 4K IPS, 100% sRGB, Thunderbolt 4, USB-C 96W, KVM switch. Professional creator monitor.', specifications: { Display: '27" 4K 3840x2160', Panel: 'IPS', 'Color Space': '100% sRGB, DCI-P3 95%', Connectivity: 'Thunderbolt 4, USB-C 96W', KVM: 'Built-in', Calibration: 'Factory', Ports: 'Thunderbolt 4, HDMI 2.0, DP 1.4' }, pros: ['Thunderbolt 4 connectivity', '4K resolution for professionals', 'KVM switch built-in', 'Excellent color accuracy'], cons: ['60Hz refresh rate', 'Premium price', 'No gaming focus'], rating: 4.5, reviews_count: 3450 },
  { name: 'MSI Optix MAG274QRF-QD', category: 'Monitors', brand: 'MSI', price: 37999, description: '27" QHD 165Hz IPS with Quantum Dot, 1ms GTG, FreeSync Premium, console-friendly.', specifications: { Display: '27" QHD 2560x1440', Panel: 'IPS Quantum Dot', 'Refresh Rate': '165Hz', 'Response Time': '1ms GTG', 'Color Space': 'DCI-P3 95%', 'Sync Tech': 'FreeSync Premium', Ports: 'HDMI 2.0b x2, DP 1.2a, USB hub' }, pros: ['Quantum Dot wide color', 'IPS fast response', 'USB hub built-in', 'Good for gaming and creative'], cons: ['Stand limited tilt/swivel', 'DCI-P3 not full coverage', 'No HDR400+ brightness'], rating: 4.3, reviews_count: 6780 },
  { name: 'ViewSonic VP2768a', category: 'Monitors', brand: 'ViewSonic', price: 42999, description: '27" QHD IPS, 100% sRGB/Rec.709, factory calibrated, USB-C 60W, height-adjustable. For color work.', specifications: { Display: '27" QHD 2560x1440', Panel: 'IPS', 'Color Accuracy': 'Delta E < 2', 'Color Space': '100% sRGB, 100% Rec.709', 'USB-C': '60W Power Delivery', Ports: 'HDMI 1.4, DP 1.2, USB-C, USB hub', Ergonomics: 'Height/Tilt/Swivel/Pivot' }, pros: ['Full ergonomic adjustability', 'Factory color calibration', 'USB-C charging', 'Built-in USB 3.1 hub'], cons: ['60Hz only', 'Basic HDR support', 'USB-C only 60W'], rating: 4.4, reviews_count: 3210 },
  { name: 'AOC 24G2', category: 'Monitors', brand: 'AOC', price: 16999, description: '24" FHD 144Hz IPS, 1ms MPRT, FreeSync, HDMI + DisplayPort. Best budget gaming monitor.', specifications: { Display: '24" FHD 1920x1080', Panel: 'IPS', 'Refresh Rate': '144Hz', 'Response Time': '1ms MPRT', 'Sync Tech': 'FreeSync', Ports: 'HDMI 1.4, VGA, DP 1.2', Stand: 'Height adjustable' }, pros: ['Excellent value gaming monitor', 'IPS colors at budget', '144Hz smooth gaming', 'Height-adjustable stand'], cons: ['FHD only (not QHD)', 'HDMI limited to 1.4', 'Basic HDR'], rating: 4.4, reviews_count: 23450 },
  { name: 'LG 32UN880-B UltraFine', category: 'Monitors', brand: 'LG', price: 79999, description: '32" 4K IPS, USB-C 96W, Thunderbolt 3, Height adjustable, Ergo stand. Premium productivity display.', specifications: { Display: '32" 4K 3840x2160', Panel: 'IPS', 'Color Space': 'DCI-P3 95%', 'USB-C': '96W Power Delivery', Connectivity: 'USB-C, HDMI 2.0, DP 1.4', Stand: 'Ergo arm-style', Weight: '7.3 kg' }, pros: ['Ergo arm stand flexible positioning', '4K resolution for professionals', 'USB-C 96W charging', 'USB hub built-in'], cons: ['Expensive', '60Hz only', 'No HDR400', 'Heavy for arm use'], rating: 4.5, reviews_count: 4560 },
  { name: 'Philips 27M2N8500', category: 'Monitors', brand: 'Philips', price: 59999, description: '27" QHD 240Hz Nano IPS, HDMI 2.1, 1ms GTG, NVIDIA G-Sync Compatible. High refresh gaming.', specifications: { Display: '27" QHD 2560x1440', Panel: 'Nano IPS', 'Refresh Rate': '240Hz', 'Response Time': '1ms GTG', HDR: 'DisplayHDR 600', 'Sync Tech': 'G-Sync Compatible', Ports: 'HDMI 2.1, DP 1.4' }, pros: ['240Hz QHD smooth competitive gaming', 'HDMI 2.1 port', 'HDR600 decent brightness', 'Nano IPS accurate colors'], cons: ['Expensive for QHD', 'Stand not height adjustable', 'Overkill for casual users'], rating: 4.3, reviews_count: 2340 },
]

const keyboards: ProductInput[] = [
  { name: 'Keychron Q1 Pro', category: 'Keyboards', brand: 'Keychron', price: 17999, description: 'QMK/VIA compatible, gasket-mounted, PBT keycaps, RGB, wireless. Best enthusiast keyboard.', specifications: { Layout: '75% (TKL)', Mount: 'Gasket', Switch: 'Gateron G Pro Red (Hot-swap)', Connectivity: 'Bluetooth 5.1 / USB-C', Battery: '4000mAh', Backlighting: 'RGB per key', Keycaps: 'Double-shot PBT' }, pros: ['Gasket mount excellent feel', 'QMK/VIA fully programmable', 'Hot-swappable switches', 'Great typing feel'], cons: ['Heavy at 1.8kg', 'No numpad', 'Complex for beginners', 'Expensive'], rating: 4.7, reviews_count: 4560 },
  { name: 'Logitech MX Keys', category: 'Keyboards', brand: 'Logitech', price: 9999, description: 'Backlit chiclet keys, multi-device support, Easy Switch, USB-C rechargeable. Best productivity keyboard.', specifications: { Layout: 'Full-size', Switch: 'Low-profile scissor', Connectivity: 'Bluetooth + USB receiver', Devices: '3 simultaneous', Battery: '10 days backlit / 5 months no backlight', Backlighting: 'Smart backlight', Weight: '810g' }, pros: ['Best productivity typing feel', 'Multi-device seamless switching', 'Smart backlighting', 'USB-C rechargeable'], cons: ['Expensive for wireless keyboard', 'Not mechanical', 'Bluetooth can drop'], rating: 4.5, reviews_count: 23450 },
  { name: 'Corsair K70 RGB Pro', category: 'Keyboards', brand: 'Corsair', price: 14999, description: 'Cherry MX switches, aircraft-grade aluminum frame, per-key RGB, USB pass-through. Gaming keyboard.', specifications: { Layout: 'Full-size', Switch: 'Cherry MX Red', Frame: 'Brushed aluminum', Connectivity: 'USB-A (detachable)', Backlighting: 'Per-key RGB', 'USB Pass-through': 'Yes', Software: 'iCUE' }, pros: ['Cherry MX switch quality', 'Solid aluminum build', 'USB pass-through', 'iCUE software advanced'], cons: ['Wired only', 'Expensive', 'iCUE can be resource heavy', 'No hot-swap'], rating: 4.4, reviews_count: 12340 },
  { name: 'Razer BlackWidow V3 Tenkeyless', category: 'Keyboards', brand: 'Razer', price: 11999, description: 'Razer Green switches (clicky), TKL form factor, Chroma RGB, compact gaming keyboard.', specifications: { Layout: 'TKL 80%', Switch: 'Razer Green (Clicky)', Connectivity: 'USB-A', Backlighting: 'Razer Chroma RGB', 'Wrist Rest': 'Optional', Software: 'Razer Synapse', Construction: 'Metal top plate' }, pros: ['Satisfying clicky switches', 'Compact TKL saves desk space', 'Chroma RGB ecosystem', 'Solid construction'], cons: ['Loud clicky switches', 'No wireless version', 'Razer switches proprietary'], rating: 4.3, reviews_count: 8907 },
  { name: 'HyperX Alloy Origins Core', category: 'Keyboards', brand: 'HyperX', price: 7999, description: 'HyperX Red switches, aircraft-grade aluminum body, TKL compact, per-key RGB, detachable cable.', specifications: { Layout: 'TKL 80%', Switch: 'HyperX Red Linear', Frame: 'Aircraft-grade aluminum', Connectivity: 'USB-C detachable', Backlighting: 'Per-key RGB', Software: 'NGENUITY', Weight: '950g' }, pros: ['Aluminum build at budget', 'Smooth linear switches', 'Detachable USB-C', 'Good price-to-quality'], cons: ['HyperX switches less known', 'Software basic', 'No wireless'], rating: 4.2, reviews_count: 15670 },
  { name: 'Royal Kludge RK68 Pro', category: 'Keyboards', brand: 'Royal Kludge', price: 5999, description: '65% layout, hot-swappable, triple-mode (BT/2.4G/USB), RGB, budget mechanical keyboard.', specifications: { Layout: '65%', Switch: 'RK Red Linear (Hot-swap)', Connectivity: 'Bluetooth 5.0 / 2.4GHz / USB-C', Battery: '3000mAh', Backlighting: 'Per-key RGB', Keycaps: 'Double-shot ABS', Modes: 'Triple mode wireless' }, pros: ['Triple wireless modes', 'Hot-swappable at budget price', '65% compact layout', 'RGB backlighting'], cons: ['ABS keycaps shine over time', 'Battery life moderate', 'RK switches not premium'], rating: 4.3, reviews_count: 28900 },
  { name: 'SteelSeries Apex Pro TKL', category: 'Keyboards', brand: 'SteelSeries', price: 16999, description: 'Adjustable actuation OmniPoint 2.0 switches, OLED display, magnetic wrist rest, TKL gaming keyboard.', specifications: { Layout: 'TKL 80%', Switch: 'OmniPoint 2.0 Adjustable', Connectivity: 'USB-A', Backlighting: 'Per-key RGB', Display: 'OLED SmartDisplay', 'Wrist Rest': 'Magnetic', Software: 'SteelSeries GG' }, pros: ['Adjustable actuation point unique', 'OLED display practical', 'Magnetic wrist rest included', 'Fastest response time switches'], cons: ['Very expensive', 'Proprietary switches', 'OLED display gimmicky for some'], rating: 4.4, reviews_count: 5670 },
  { name: 'Ducky One 3 TKL', category: 'Keyboards', brand: 'Ducky', price: 9999, description: 'Premium TKL with hot-swap, sound dampening foam, PBT shine-through keycaps, Cherry MX switches.', specifications: { Layout: 'TKL 80%', Switch: 'Cherry MX Red (Hot-swap)', Mount: 'Sandwich with foam', Keycaps: 'PBT Double-shot', Connectivity: 'USB-C detachable', Backlighting: 'Per-key RGB', Extras: 'Sound dampening foam' }, pros: ['Premium build for the price', 'Sound-dampened typing', 'PBT keycaps included', 'Hot-swap Cherry MX'], cons: ['No wireless option', 'Limited software', 'Ducky brand harder to find in India'], rating: 4.6, reviews_count: 7890 },
  { name: 'Logitech G915 TKL', category: 'Keyboards', brand: 'Logitech', price: 18999, description: 'GL mechanical switches, ultra-thin design, LIGHTSPEED wireless, 40-hour battery, premium TKL.', specifications: { Layout: 'TKL 80%', Switch: 'Logitech GL Linear (Low-profile)', Connectivity: 'LIGHTSPEED 2.4GHz / Bluetooth', Battery: '40 hours', Backlighting: 'Per-key RGB Lightsync', Weight: '810g', Thickness: '22mm' }, pros: ['Ultra-thin low-profile design', 'LIGHTSPEED 1ms wireless', '40-hour battery', 'Premium build quality'], cons: ['Very expensive', 'Low-profile switches not for everyone', 'Proprietary GL switches'], rating: 4.5, reviews_count: 9870 },
  { name: 'Keychron K2 V2', category: 'Keyboards', brand: 'Keychron', price: 7999, description: '75% layout, Bluetooth 5.1, hot-swap, RGB backlight, PBT keycaps. Best value wireless mechanical.', specifications: { Layout: '75%', Switch: 'Gateron G Pro Red (Hot-swap)', Connectivity: 'Bluetooth 5.1 / USB-C', Battery: '4000mAh', Backlighting: 'RGB per key', Keycaps: 'Double-shot PBT', OS: 'Mac / Win compatible' }, pros: ['Best value wireless mechanical', 'Hot-swappable', 'Mac and Windows compatible', 'Compact 75% layout'], cons: ['Tray mount less premium feel', 'ABS version cheaper option', 'No 2.4GHz option'], rating: 4.5, reviews_count: 34560 },
]

const mice: ProductInput[] = [
  { name: 'Logitech MX Master 3S', category: 'Mice', brand: 'Logitech', price: 8995, description: '8K DPI sensor, MagSpeed scroll wheel, quiet clicks, USB-C, Bluetooth + USB receiver. Best productivity mouse.', specifications: { DPI: '200-8000 DPI', Buttons: '7 programmable', Connectivity: 'Bluetooth + USB receiver', Battery: '70 days', Charging: 'USB-C', Scroll: 'MagSpeed electromagnetic', Weight: '141g' }, pros: ['MagSpeed scroll exceptional', 'Multi-device support', 'Quiet click switches', 'Ergonomic design'], cons: ['Expensive', 'Large for small hands', 'Heavy at 141g', 'Right-handed only'], rating: 4.7, reviews_count: 18900 },
  { name: 'Razer DeathAdder V3 HyperSpeed', category: 'Mice', brand: 'Razer', price: 6999, description: 'Focus Pro 30K optical sensor, 30000 DPI, 90-hour battery, ultra-lightweight. Gaming wireless mouse.', specifications: { Sensor: 'Focus Pro 30K Optical', DPI: '100-30000', Buttons: '6', Connectivity: 'Razer HyperSpeed Wireless', Battery: '90 hours', Weight: '64g', Polling: '125-4000Hz' }, pros: ['Lightweight 64g', 'Excellent 90-hour battery', 'Focus Pro 30K sensor', 'Ergonomic shape'], cons: ['Proprietary HyperSpeed dongle', 'No Bluetooth', 'No RGB', 'Right-handed only'], rating: 4.5, reviews_count: 9870 },
  { name: 'SteelSeries Aerox 3', category: 'Mice', brand: 'SteelSeries', price: 5499, description: 'Ultra-lightweight 59g honeycomb design, TrueMove Core sensor, IP54 rated, USB-C.', specifications: { Sensor: 'SteelSeries TrueMove Core', DPI: '100-8500', Weight: '59g', Connectivity: 'Wired USB-C', 'Water Resistance': 'IP54', Buttons: '6', RGB: 'TrueRGB' }, pros: ['Ultra-lightweight 59g', 'IP54 splash resistant', 'Budget gaming mouse', 'USB-C cable'], cons: ['Wired only', 'Limited DPI range', 'Honeycomb shell collects dust'], rating: 4.3, reviews_count: 7654 },
  { name: 'Logitech G Pro X Superlight 2', category: 'Mice', brand: 'Logitech', price: 12999, description: 'HERO 2 sensor, 32000 DPI, ultra-lightweight 60g, 95-hour battery, ambidextrous wireless.', specifications: { Sensor: 'HERO 2 32K', DPI: '100-32000', Weight: '60g', Connectivity: 'Lightspeed Wireless', Battery: '95 hours', Buttons: '5', Ambidextrous: 'Yes' }, pros: ['60g ultralight for wireless', 'HERO 2 best-in-class sensor', 'Ambidextrous design', '95-hour battery'], cons: ['Very expensive', 'No side buttons for lefties', 'Minimalist no RGB'], rating: 4.7, reviews_count: 8907 },
  { name: 'Corsair Harpoon RGB Pro', category: 'Mice', brand: 'Corsair', price: 2499, description: 'Budget gaming mouse with 12000 DPI PixArt sensor, RGB, lightweight 99g, 6 buttons.', specifications: { Sensor: 'PixArt PMW3327', DPI: '100-12000', Weight: '99g', Connectivity: 'Wired USB', Buttons: '6', RGB: 'Single zone RGB', Software: 'iCUE' }, pros: ['Very affordable gaming mouse', 'Reliable PixArt sensor', 'RGB lighting', 'iCUE software'], cons: ['Wired only', 'Basic sensor vs premium', 'No ambidextrous option', 'Cable quality average'], rating: 4.0, reviews_count: 34560 },
  { name: 'Glorious Model O Wireless', category: 'Mice', brand: 'Glorious', price: 7999, description: 'Honeycomb design, 71g ultra-lightweight, BAMF 2.0 sensor, 2.4GHz + Bluetooth wireless.', specifications: { Sensor: 'BAMF 2.0 26K DPI', DPI: '100-26000', Weight: '71g', Connectivity: '2.4GHz + Bluetooth', Battery: '75 hours', Buttons: '6', RGB: 'RGB lighting' }, pros: ['71g lightweight wireless', 'BAMF 2.0 high precision', 'Both 2.4GHz and Bluetooth', 'Good battery life'], cons: ['Honeycomb shows dust easily', 'Software Glorious Core limited', 'Grip tape not included'], rating: 4.4, reviews_count: 6780 },
  { name: 'Zowie EC2-C', category: 'Mice', brand: 'Zowie', price: 5999, description: 'Esports ergonomic mouse, PMW 3360 sensor, 3200 DPI, no software required, plug-and-play.', specifications: { Sensor: 'PMW 3360', DPI: '400-3200', Weight: '95g', Connectivity: 'Wired USB', Buttons: '5', Software: 'None required', Skates: 'PTFE' }, pros: ['Zero software hassle', 'Proven PMW3360 sensor', 'Ergonomic esports shape', 'PTFE feet smooth glide'], cons: ['No RGB', 'No wireless', 'DPI limited to 3200', 'Basic design'], rating: 4.5, reviews_count: 12340 },
  { name: 'Logitech G203 Lightsync', category: 'Mice', brand: 'Logitech', price: 1995, description: 'Budget gaming mouse with 8000 DPI Mercury sensor, 6 buttons, RGB, classic gaming shape.', specifications: { Sensor: 'Mercury optical', DPI: '200-8000', Weight: '90g', Connectivity: 'Wired USB', Buttons: '6', RGB: 'LIGHTSYNC RGB', Software: 'G Hub' }, pros: ['Very budget friendly', 'Classic ergonomic shape', 'RGB Lightsync', 'G Hub software access'], cons: ['Wired only', 'Budget sensor', 'No side texture', 'No scroll lock button'], rating: 4.2, reviews_count: 45670 },
  { name: 'Razer Viper V3 HyperSpeed', category: 'Mice', brand: 'Razer', price: 5499, description: 'Focus Pro 30K sensor, 280-hour battery, ambidextrous shape, ultra-lightweight wireless gaming mouse.', specifications: { Sensor: 'Focus Pro 30K', DPI: '100-30000', Weight: '82g', Connectivity: 'HyperSpeed Wireless', Battery: '280 hours', Buttons: '6', Ambidextrous: 'Yes' }, pros: ['280-hour incredible battery', 'Ambidextrous design', 'Focus Pro 30K sensor', 'Affordable wireless gaming'], cons: ['No Bluetooth', 'No RGB', 'HyperSpeed dongle required', 'AA battery adds weight'], rating: 4.5, reviews_count: 9870 },
  { name: 'HyperX Pulsefire Haste 2', category: 'Mice', brand: 'HyperX', price: 4999, description: 'Honeycomb design, HyperFlex 2 cable, TrueMove Pro 26K sensor, 61g ultralight wired mouse.', specifications: { Sensor: 'TrueMove Pro 26K', DPI: '100-26000', Weight: '61g', Connectivity: 'Wired USB-C', Buttons: '6', Cable: 'HyperFlex 2 Ultra-flexible', Skates: 'PTFE' }, pros: ['61g ultralight', 'Excellent HyperFlex cable', 'High precision 26K sensor', 'Budget ultralight option'], cons: ['Wired only', 'Honeycomb shows dust', 'No wireless version'], rating: 4.4, reviews_count: 7890 },
]

const gamingAccessories: ProductInput[] = [
  { name: 'Razer Kraken V3 HyperSense', category: 'Gaming Accessories', brand: 'Razer', price: 9999, description: 'Haptic feedback headset, THX Spatial Audio, TriForce Titanium drivers, USB gaming headset.', specifications: { Type: 'Gaming Headset', Driver: 'TriForce Titanium 50mm', Audio: 'THX Spatial Audio', Microphone: 'HyperClear Cardioid', Connectivity: 'USB-A', Feature: 'HyperSense Haptic Feedback', Weight: '322g' }, pros: ['Haptic bass feedback immersive', 'THX Spatial surround sound', 'Good microphone quality', 'Chroma RGB'], cons: ['USB only no 3.5mm', 'Heavy at 322g', 'Expensive for headset', 'PC only haptics'], rating: 4.2, reviews_count: 5678 },
  { name: 'Xbox Wireless Controller', category: 'Gaming Accessories', brand: 'Microsoft', price: 5490, description: 'Works with Xbox Series X|S, Xbox One, Windows PC. Textured grip, share button, USB-C.', specifications: { Compatibility: 'Xbox Series X|S, Xbox One, PC', Connectivity: 'Wireless + USB-C', Battery: '40 hours AA batteries', 'Share Button': 'Yes', 'Haptic Triggers': 'Impulse triggers', 'Textured Grip': 'Yes' }, pros: ['Best ergonomics in controllers', 'Wide compatibility', 'Impulse triggers', 'USB-C charging'], cons: ['AA batteries no built-in rechargeable', 'No headphone jack', 'Basic rechargeable sold separately'], rating: 4.6, reviews_count: 34560 },
  { name: 'SteelSeries Arctis Nova Pro', category: 'Gaming Accessories', brand: 'SteelSeries', price: 24999, description: 'High-fidelity gaming headset, active noise cancellation, ClearCast AI mic, dual wireless.', specifications: { Driver: 'High-fidelity 40mm', ANC: 'Active Noise Cancellation', Microphone: 'ClearCast AI', Connectivity: 'Dual Wireless (2.4GHz + Bluetooth)', Battery: '22hr + hot-swap', Mobile: 'Compatible' }, pros: ['ANC in gaming headset', 'Hot-swap batteries', 'Dual wireless PC + mobile', 'Premium sound quality'], cons: ['Very expensive', 'Complex setup', 'Base station required'], rating: 4.5, reviews_count: 3456 },
  { name: 'Corsair Scimitar Elite', category: 'Gaming Accessories', brand: 'Corsair', price: 7999, description: '17-button MMO gaming mouse, 18000 DPI, Key Slider system for button customization.', specifications: { Sensor: 'PixArt PAW3392', DPI: '100-18000', Buttons: '17 programmable', Connectivity: 'Wired USB', 'Side Buttons': '12 on side panel', 'Key Slider': 'Adjustable position', RGB: 'iCUE per-zone' }, pros: ['17 programmable buttons for MMO', 'Key Slider unique feature', 'Excellent for MMO games', 'iCUE software integration'], cons: ['Very heavy 144g', 'Right-handed only', 'Too many buttons for FPS'], rating: 4.2, reviews_count: 7890 },
  { name: 'Logitech G29 Driving Force', category: 'Gaming Accessories', brand: 'Logitech', price: 26990, description: 'Racing wheel with 900° rotation, force feedback, leather-wrapped wheel, pedal set.', specifications: { Rotation: '900° lock-to-lock', 'Force Feedback': 'Dual-motor', Material: 'Leather-wrapped wheel', Pedals: '3 included (clutch, brake, gas)', Compatibility: 'PS3, PS4, PS5, PC', Connectivity: 'USB-A', 'Shift Paddles': 'Stainless steel' }, pros: ['Authentic driving experience', 'Force feedback quality', 'Leather wheel feel', 'Compatible with multiple platforms'], cons: ['Expensive', 'Requires mounting/clamping', 'No H-pattern shifter included'], rating: 4.5, reviews_count: 8907 },
  { name: 'PlayStation DualSense Controller', category: 'Gaming Accessories', brand: 'Sony', price: 5790, description: 'Adaptive triggers, haptic feedback, built-in mic, USB-C charging. Best console controller.', specifications: { Compatibility: 'PS5, PC', Connectivity: 'Bluetooth 5.1 + USB-C', Battery: '12 hours', 'Adaptive Triggers': 'Yes', 'Haptic Feedback': 'Yes', Microphone: 'Built-in', 'USB-C': 'Yes' }, pros: ['Adaptive triggers revolutionary', 'Best haptic feedback in controller', 'Built-in microphone', 'USB-C charging'], cons: ['Battery life 12hrs shorter than Xbox', 'Heavy compared to Xbox controller', 'No rechargeable AA option'], rating: 4.7, reviews_count: 56780 },
  { name: 'Turtle Beach Stealth 600 Gen 2', category: 'Gaming Accessories', brand: 'Turtle Beach', price: 6999, description: 'Wireless gaming headset, Superhuman Hearing, 15hr battery, ProSpecs glasses comfort, 50mm drivers.', specifications: { Type: 'Gaming Headset', Driver: '50mm', Connectivity: '2.4GHz Wireless', Battery: '15 hours', Compatibility: 'Xbox, PC, PlayStation', Feature: 'Superhuman Hearing mode', Weight: '350g' }, pros: ['Superhuman Hearing competitive advantage', 'Multi-platform wireless', 'ProSpecs glasses comfort', 'Budget wireless gaming headset'], cons: ['Average sound quality vs premium', 'Heavy 350g', 'No ANC', 'Plastic build'], rating: 4.1, reviews_count: 23450 },
  { name: 'Razer Goliathus Extended Chroma', category: 'Gaming Accessories', brand: 'Razer', price: 4999, description: 'Extended gaming mousepad with RGB edge lighting, micro-textured surface, anti-fray stitching.', specifications: { Size: '920mm x 294mm x 3mm', Surface: 'Micro-textured cloth', RGB: 'Chroma edge lighting', Base: 'Non-slip rubber', Connectivity: 'USB-A for RGB', Compatible: 'Razer Synapse' }, pros: ['Large extended size covers full desk', 'Chroma RGB impressive aesthetic', 'Consistent micro-textured surface', 'Anti-fray edges'], cons: ['USB required for RGB only', 'Expensive for a mousepad', 'RGB adds cable clutter'], rating: 4.3, reviews_count: 12340 },
  { name: 'Elgato Stream Deck MK.2', category: 'Gaming Accessories', brand: 'Elgato', price: 14999, description: '15 customizable LCD keys, stream control, one-touch scene switching, Elgato plugin ecosystem.', specifications: { Keys: '15 LCD customizable', Display: 'Individual LCD per key', Connectivity: 'USB-A', Software: 'Stream Deck plugin ecosystem', Compatibility: 'Windows, macOS', Dimensions: '118mm x 84mm', Material: 'Plastic + rubber base' }, pros: ['Streamlining workflow game-changer', 'LCD keys show custom icons', 'Massive plugin ecosystem', 'Works for streaming and productivity'], cons: ['Expensive for what it is', 'Software learning curve', 'Not just for gamers but marketed that way'], rating: 4.6, reviews_count: 18900 },
  { name: 'HyperX Cloud Alpha Wireless', category: 'Gaming Accessories', brand: 'HyperX', price: 14999, description: '300-hour battery wireless gaming headset, dual-chamber drivers, Discord certified mic, 2.4GHz.', specifications: { Type: 'Gaming Headset', Driver: 'Dual-chamber 50mm', Connectivity: '2.4GHz Wireless', Battery: '300 hours', Microphone: 'Detachable Discord certified', Compatibility: 'PC, PS4, PS5', Weight: '309g' }, pros: ['300-hour battery class-leading', 'Dual-chamber audio excellent', 'Discord certified mic', 'Comfortable for long sessions'], cons: ['2.4GHz only no Bluetooth', 'PC/PS only not Xbox', 'Heavy 309g', 'Not the most premium audio'], rating: 4.5, reviews_count: 15670 },
]

async function seed() {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.error('❌ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in environment.')
    console.error('   Copy .env.example to .env.local and fill in the values.')
    process.exit(1)
  }

  console.log('🌱 Starting product seed...')

  // Idempotency guard — skip if already seeded
  const { count: existing } = await supabase
    .from('products')
    .select('*', { count: 'exact', head: true })

  if (existing && existing >= 50) {
    console.log(`✅ Database already has ${existing} products. Skipping seed.`)
    console.log('   To re-seed, delete existing products first.')
    process.exit(0)
  }

  const allProducts: ProductInput[] = [
    ...laptops,
    ...smartphones,
    ...headphones,
    ...tablets,
    ...smartwatches,
    ...cameras,
    ...monitors,
    ...keyboards,
    ...mice,
    ...gamingAccessories,
  ]

  const productData = allProducts.map(p => ({
    ...p,
    currency: 'INR',
    image_url: '',
    amazon_link: p.amazon_link || makeAmazonLink(`${p.brand} ${p.name}`),
    flipkart_link: p.flipkart_link || makeFlipkartLink(`${p.brand} ${p.name}`),
    affiliate_enabled: true,
    in_stock: p.in_stock ?? true,
  }))

  console.log(`📦 Inserting ${productData.length} products...`)

  const chunkSize = 50
  for (let i = 0; i < productData.length; i += chunkSize) {
    const chunk = productData.slice(i, i + chunkSize)
    const { error } = await supabase.from('products').insert(chunk)
    if (error) {
      console.error(`❌ Error inserting chunk ${i}:`, error.message)
    } else {
      console.log(`✅ Inserted products ${i + 1} to ${Math.min(i + chunkSize, productData.length)}`)
    }
  }

  const { count: final } = await supabase
    .from('products')
    .select('*', { count: 'exact', head: true })

  console.log(`🎉 Seeding complete! ${final} products now in database.`)
}

seed().catch(console.error)
